services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mpp\PreventgoBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests,vendor}'